#pragma once
#include <jni/array/JNIBooleanArray.h>
#include <jni/array/JNIByteArray.h>
#include <jni/array/JNICharArray.h>
#include <jni/array/JNIShortArray.h>
#include <jni/array/JNIIntArray.h>
#include <jni/array/JNILongArray.h>
#include <jni/array/JNIFloatArray.h>
#include <jni/array/JNIDoubleArray.h>
#include <jni/array/JNIStringArray.h>