#pragma once
#include <jni/field/JNIBooleanArrayField.h>
#include <jni/field/JNIBooleanField.h>
#include <jni/field/JNIByteArrayField.h>
#include <jni/field/JNIByteField.h>
#include <jni/field/JNICharArrayField.h>
#include <jni/field/JNICharField.h>
#include <jni/field/JNIShortArrayField.h>
#include <jni/field/JNIShortField.h>
#include <jni/field/JNIIntArrayField.h>
#include <jni/field/JNIIntField.h>
#include <jni/field/JNILongArrayField.h>
#include <jni/field/JNILongField.h>
#include <jni/field/JNIFloatArrayField.h>
#include <jni/field/JNIFloatField.h>
#include <jni/field/JNIDoubleArrayField.h>
#include <jni/field/JNIDoubleField.h>
#include <jni/field/JNIStringArrayField.h>
#include <jni/field/JNIStringField.h>